redis:
    image: redis

db:
    image: postgress:9.4
    port:
        - 5367:5324

vote:
    image: voteing-app
    ports:
        - 5000:80
    links:
        - redis

result:
    image: result
    ports:
        - 5001:80
    links:
        - db


worker:
    image: worker
    links:
        - db
        - redis